sudo: required
language: node_js
node_js: stable
cache: npm
script: bash ./deploy.sh
branches:
  only:
  - master
notifications:
  email: true
env:
  global:
    secure: aU1JaYltU6Tj7W140JQE5L4dw7VXqk5fB/yjvYQ89pQi7jswxGpUZuGkRRlkQoZk0maDBQG1vVl4EM1+Y0gY4uQJ0ie4VEEmnORc/5o4WfTlJwthYWla0FxayrtPng775aGf2o33K8XghysQkYDGQw3nrfVVgGHYGndoT09BPXIsKU95czHEkXy7hjvUeoPM8CbulMd/n4hSbPVAhHU07JXdgm8BLH1tcSyO/Kis3ew3Y/aa71SHgirTOacWxYqHdQgnrghGh1O95K2IZEKgp6GWOWWM5D4h/y8FuMD1rpA2LQq8agCwHi9a4tmCn9MiJcSXh0BI3jRPPCkbcn8u9PaO5z9b7B7NL3xVLmT9X/mdT6psAg0rTgOkzpsERifrDr2VnUf7v9QBrFCK06OBVIT2YJZq6g1iXMxNsANgbEEsFREU0DvfGobThPDhJcvNkXU1CsonZU6mGUYQwo8Aauth75N0q/HLR8H33i3WoQ27AP7tTjvu/2w1/bYSz9socHUj+7kIysQ4dFwvoUwPm7G1alwO52bXyl/66Hy9glkezBxWGYix0oj+kLmeExdMt415eLnlmsTN1qVsDv9LHVGNCGDn6xrh7t3Jfqae0t7Hy6Uy+U5GvacFV4mKmFzHiwAZ16KN/alrBgKmvrUxqxJV0wiNH31MC7v1ZSw4Jxs=
